services:
  luni:
    env_file: ".env"
    build: .
    ports:
      - "8000:8000"
    volumes:
      - chroma_docker:/chroma
      - hf_models:/models
    depends_on:
      - mongo

  mongo:
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - mongodb7_docker:/data/db

volumes:
  chroma_docker:
  mongodb7_docker:
  hf_models:
