services:
  study_bucket:
    env_file: ".env"
    build: .
    ports:
      - "8000:8000"
    volumes:
      - chroma_docker:/chroma
    depends_on:
      - mongo
  mongo:
    ports:
      - "27017:27017"
    image: mongo
    volumes:
      - mongodb_docker:/data/db
volumes:
  chroma_docker:  
  mongodb_docker:
